### ISSUE TITLE
Inline array definitions produce invalid MSL syntax

### ISSUE THREAD

**Issue by csmartdalton86** [KhronosGroup/MoltenVK#145]
The SPIR-V -> MSL converter produces MSL with inline array definitions that look like:

`float2 _28[2] = float2[]{ a, b };`

This appears similar to the GLSL syntax for inline array definitions, however it is not valid MSL.

------------ Shader conversion logs ---------------------

[mvk-info] Converting SPIR-V:
```
; SPIR-V
; Version: 1.0
; Generator: Khronos; 0
; Bound: 43
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %2 "main" %3 %11 %13 %14
               OpSourceExtension "GL_ARB_separate_shader_objects"
               OpSourceExtension "GL_ARB_shading_language_420pack"
               OpName %4 "sk_PerVertex"
               OpMemberName %4 0 "sk_Position"
               OpMemberName %4 1 "sk_PointSize"
               OpMemberName %4 2 "sk_ClipDistance"
               OpName %11 "sk_VertexID"
               OpName %13 "sk_InstanceID"
               OpName %14 "X"
               OpName %2 "main"
               OpName %19 "x"
               OpName %29 "x0"
               OpDecorate %7 ArrayStride 16
               OpMemberDecorate %4 0 BuiltIn Position
               OpMemberDecorate %4 1 BuiltIn PointSize
               OpMemberDecorate %4 2 BuiltIn ClipDistance
               OpDecorate %4 Block
               OpDecorate %11 BuiltIn VertexIndex
               OpDecorate %13 BuiltIn InstanceIndex
               OpDecorate %14 Location 0
               OpDecorate %21 ArrayStride 16
          %6 = OpTypeFloat 32
          %5 = OpTypeVector %6 4
          %9 = OpTypeInt 32 1
          %8 = OpConstant %9 1
          %7 = OpTypeArray %6 %8
          %4 = OpTypeStruct %5 %6 %7
         %10 = OpTypePointer Output %4
          %3 = OpVariable %10 Output
         %12 = OpTypePointer Input %9
         %11 = OpVariable %12 Input
         %13 = OpVariable %12 Input
         %15 = OpTypePointer Input %5
         %14 = OpVariable %15 Input
         %16 = OpTypeVoid
         %17 = OpTypeFunction %16
         %22 = OpTypeVector %6 2
         %23 = OpConstant %9 2
         %21 = OpTypeArray %22 %23
         %20 = OpTypePointer Function %21
         %30 = OpTypePointer Function %22
         %31 = OpConstant %9 0
         %38 = OpConstant %6 0
         %39 = OpConstant %6 1
         %42 = OpTypePointer Output %5
          %2 = OpFunction %16 None %17
         %18 = OpLabel
         %19 = OpVariable %20 Function
         %29 = OpVariable %30 Function
         %24 = OpLoad %5 %14
         %25 = OpVectorShuffle %22 %24 %24 0 1
         %26 = OpLoad %5 %14
         %27 = OpVectorShuffle %22 %26 %26 2 3
         %28 = OpCompositeConstruct %21 %25 %27
               OpStore %19 %28
         %32 = OpAccessChain %30 %19 %31
         %33 = OpLoad %22 %32
               OpStore %29 %33
         %34 = OpLoad %22 %29
         %35 = OpCompositeExtract %6 %34 0
         %36 = OpLoad %22 %29
         %37 = OpCompositeExtract %6 %36 1
         %40 = OpCompositeConstruct %5 %35 %37 %38 %39
         %41 = OpAccessChain %42 %3 %31
               OpStore %41 %40
               OpReturn
               OpFunctionEnd
```

End SPIR-V

Converted MSL:
```
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_in
{
    float4 X [[attribute(0)]];
};

struct main0_out
{
    float4 gl_Position [[position]];
};

// Implementation of an array copy function to cover GLSL's ability to copy an array via assignment.
template<typename T, uint N>
void spvArrayCopy(thread T (&dst)[N], thread const T (&src)[N])
{
    for (uint i = 0; i < N; dst[i] = src[i], i++);
}

// An overload for constant arrays.
template<typename T, uint N>
void spvArrayCopyConstant(thread T (&dst)[N], constant T (&src)[N])
{
    for (uint i = 0; i < N; dst[i] = src[i], i++);
}

vertex main0_out main0(main0_in in [[stage_in]], uint gl_VertexIndex [[vertex_id]], uint gl_InstanceIndex [[instance_id]])
{
    main0_out out = {};
    float2 _28[2] = float2[]{ in.X.xy, in.X.zw };
    float2 x[2];
    spvArrayCopy(x, _28);
    float2 x0 = x[0];
    out.gl_Position = float4(x0.x, x0.y, 0.0, 1.0);
    out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
    return out;
}

```

End MSL

Estimated original GLSL:
```
#version 450

uniform int SPIRV_Cross_BaseInstance;
layout(location = 0) in vec4 X;

void main()
{
    vec2 x[2] = vec2[](X.xy, X.zw);
    vec2 x0 = x[0];
    gl_Position = vec4(x0.x, x0.y, 0.0, 1.0);
}

```

End GLSL

[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Shader module compilation failed (code 3):

Compilation failed: 

**program_source:35:21: error:** unexpected type name 'float2': expected expression
    float2 _28[2] = float2[]{ in.X.xy, in.X.zw };
                    ^
**program_source:35:28: error:** expected expression
    float2 _28[2] = float2[]{ in.X.xy, in.X.zw };

**Comment by billhollings** [comment]
@csmartdalton86 

Can you post this (and other shader conversion issues in the future) to [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross/issues), please?

If you have a shader file (GLSL or SPIR-V) that demonstrates the issue, it will help get it resolved faster if you can provide it in the issue posting.

Thanks.

**Comment by csmartdalton86** [comment]
Posted as https://github.com/KhronosGroup/SPIRV-Cross/issues/558

Thanks!

**Comment by billhollings** [comment]
@csmartdalton86 

https://github.com/KhronosGroup/SPIRV-Cross/issues/558 has been resolved.

Please confirm at close this issue if that meets your needs.

**Comment by csmartdalton86** [comment]
Still broken. I see ExternalRevisions/SPIRV-Cross_repo_revision is:

7796a9f3ec94733830ad8c648157a3b1c5693e34

If I bump that locally to:

9279750a1d6332ed02dc32f6969a714f4ec906cb

Then run ./fetchDependencies again, everything looks fixed.

Does that file need to be updated manually?

**Comment by billhollings** [comment]
Yeah...sorry...I was going through the Issues list and I jumped the gun there!

**Comment by billhollings** [comment]
Fixed in PR #149. Please retest and close.
