### ISSUE TITLE
2019 MacBook Pro - Memory Leaks during vkCreateInstance

### ISSUE THREAD

**Issue by angkaidev** [KhronosGroup/MoltenVK#1978]
Hi! I am new to working with Vulkan, and I was just following the tutorial, and doing some tests to make sure that I am doing things correctly. Of those tests, I ran leaks on my program, and found that there were 4 memory leaks. I made a trivial version of the code that covers all of the memory leaks, and have attached the leaks results below:

```
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

#include <iostream>
#include <stdexcept>
#include <vector>

const std::vector<const char*> validationLayers = {
    "VK_LAYER_KHRONOS_validation"
};

class Engine {
public:
    void run() {
        glfwInit();
        
        glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
        glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);
        
        window = glfwCreateWindow(800, 600, "Application", nullptr, nullptr);

        if(!checkValidationLayerSupport()) {
            throw std::runtime_error("Validation layers requested, but not available!");
        }

        VkApplicationInfo appInfo = {
            .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
            .pApplicationName = "Application",
            .applicationVersion = VK_MAKE_VERSION(1, 3, 0),
            .pEngineName = "No Engine",
            .engineVersion = VK_MAKE_VERSION(1, 3, 0),
            .apiVersion = VK_API_VERSION_1_3
        };
        
        std::vector<const char*> extensions = getRequiredExtensions();
        
        VkInstanceCreateInfo createInfo = {
            .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
            .pApplicationInfo = &appInfo,
            .enabledExtensionCount = static_cast<uint32_t>(extensions.size()),
            .ppEnabledExtensionNames = extensions.data(),
            .flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR
        };
        
        createInfo.enabledLayerCount = static_cast<uint32_t>(validationLayers.size());
        createInfo.ppEnabledLayerNames = validationLayers.data();
        
        createInfo.pNext = (VkDebugUtilsMessengerCreateInfoEXT*) &debugCreateInfo;

        if(vkCreateInstance (&createInfo, nullptr, &instance) != VK_SUCCESS) {
            throw std::runtime_error("Failed to create Vulkan instance!");
        }

        vkDestroyInstance(instance, nullptr);
        glfwDestroyWindow(window);
        glfwTerminate();
    }

private:
    GLFWwindow* window;
    VkInstance instance;
    VkDebugUtilsMessengerEXT debugMessenger;

    bool checkValidationLayerSupport() {
        uint32_t layerCount;
        vkEnumerateInstanceLayerProperties(&layerCount, nullptr);
        std::vector<VkLayerProperties> availableLayers(layerCount);
        vkEnumerateInstanceLayerProperties(&layerCount, availableLayers.data());
        
        for(const char* layerName : validationLayers) {
            bool layerFound = false;
            
            for(const VkLayerProperties& layerProperties : availableLayers) {
                if(strcmp(layerName,  layerProperties.layerName) == 0) {
                    layerFound = true;
                    break;
                }
            }
            
            if(!layerFound) {
                std::cout << "Unable to find validation layer: " << layerName << std::endl;
                return false;
            }
        }
        
        return true;
    }

    std::vector<const char*> getRequiredExtensions() {
        uint32_t glfwExtensionCount = 0;
        const char** glfwExtensions = glfwGetRequiredInstanceExtensions(&glfwExtensionCount);
        std::vector<const char*> extensions(glfwExtensions, glfwExtensions + glfwExtensionCount);
        
        extensions.push_back(VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME);
        extensions.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
        
        return extensions;
    }

    static VKAPI_ATTR VkBool32 VKAPI_CALL debugCallback(VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity, VkDebugUtilsMessageTypeFlagsEXT messageType, const VkDebugUtilsMessengerCallbackDataEXT* pCallbackData, void* pUserData) {
        if(messageSeverity >= VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT) {
            std::cerr << "Validation Layer: " << pCallbackData->pMessage << std::endl;
        }
        
        return VK_FALSE;
    }

    inline static const VkDebugUtilsMessengerCreateInfoEXT debugCreateInfo = {
        .sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT,
        .messageSeverity = VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT | VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT | VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT,
        .messageType = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT | VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT | VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT,
        .pfnUserCallback = debugCallback
    };
};

int main() {
    Engine app;
    
    try {
        app.run();
    } catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        return EXIT_FAILURE;
    }
    
    return EXIT_SUCCESS;
}
```

All of the leaks happen in MoltenVK as a result of calling vkCreateInstance.
[leak_results.txt](https://github.com/KhronosGroup/MoltenVK/files/12037679/leak_results.txt)

**Comment by AntarticCoder** [comment]
I'm not sure if MoltenVK supports 1.3, I'm using 1.2. Try that out.

**Comment by billhollings** [comment]
@angkaidev Thanks for reporting this. 

Apple had/has a known leak on its counter sets. We made use of a work-around, and then Apple fixed it. So the presence of the leak depends the platform and OS version. For the most part, the leak is fixed, and it is small, so we've been living with it on the edge cases where it does appear.

Can you provide some more details about the platform and OS version you are running this on, please? From your leak tool dump it looks like you're running Intel for both CPU and GPU. What OS version?

**Comment by angkaidev** [comment]
Hi @AntarticCoder @billhollings, thank you for the quick reply!

I tried using 1.2 and unfortunately it still does not work. I am running Ventura 13.4.1

**Comment by AntarticCoder** [comment]
I'm a bit stumped on this, but why don't you try [this](https://vulkan-tutorial.com/code/02_validation_layers.cpp). This from vulkan-tutorial so it should be valid code most likely. Just comment out your code, and copy and paste. Then see what your leak dump tool says.

**Comment by angkaidev** [comment]
@AntarticCoder Unfortunately, the leaks are still the same.

**Comment by philippremy** [comment]
Hey, it appears like this is still not properly fixed?

I looked into it a little and figured that (for whatever reason) the autoreleasepool blocks in`MVKInstance::MVKInstance` and `MVKPhysicalDevice::initCounterSets` were not working correctly. 

I tried to switch to manual memory management and explicitly released the `NSArray<id<MTLDevice>>*` in `MVKInstance::MVKInstance` and moved the `NSArray<id<MTLCounterSet>>* counterSets = _mtlDevice.counterSets;` call directly into the for-each-loop in `MVKPhysicalDevice::initCounterSets`. 

For me (MacBook Pro Late 2017, Radeon Pro 560 and Intel HD Graphics 630), that actually removed the leaks. However, I can't test whether this still works for the special Intel GPUs which suffer from the retain bug in `MVKPhysicalDevice::initCounterSets` and for Apple Silicon GPUs.

So I'd really appreciate if someone could check that :). I would submit a PR in that case.

The current fork lives here: https://github.com/philippremy/MoltenVK
