### ISSUE TITLE
VK_FORMAT_R32G32B32_SFLOAT stopped being a supported vertex buffer format after update to 1.1.82.0

### ISSUE THREAD

**Issue by olegyadrov** [KhronosGroup/MoltenVK#218]
I updated LunarG Vulkan SDK on my mac to the latest version (vulkansdk-macos-1.1.82.0) today and my vulkan-tutorial-based app stopped to function properly:

`validation layer: [ VUID-VkVertexInputAttributeDescription-format-00623 ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines: pCreateInfo[0].pVertexInputState->vertexAttributeDescriptions[1].format (VK_FORMAT_R32G32B32_SFLOAT) is not a supported vertex buffer format. The spec valid usage text states 'format must be allowed as a vertex buffer format, as specified by the VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT flag in VkFormatProperties::bufferFeatures returned by vkGetPhysicalDeviceFormatProperties' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkVertexInputAttributeDescription-format-00623)`

Despite VK_FORMAT_R32G32B32_SFLOAT is "not supported", the app runs normally but crashes on window resize.

I double checked, same code works fine with vulkansdk-macos-1.1.77.0, so I guess it's a bug in the latest MoltenVK.

https://vulkan-tutorial.com/Vertex_buffers/Vertex_input_description

```
attributeDescriptions[1].binding = 0;
attributeDescriptions[1].location = 1;
attributeDescriptions[1].format = VK_FORMAT_R32G32B32_SFLOAT;
attributeDescriptions[1].offset = offsetof(Vertex, color);
```

**Comment by billhollings** [comment]
Fixed in PR #219. Please retest and close.

**Comment by olegyadrov** [comment]
OK, I checked out the master branch and built MoltenVK (for first time, btw). Validation layers don't complain for VK_FORMAT_R32G32B32_SFLOAT anymore, but my app still freezes on window resize. I'll open a new issue for that.

**Comment by olegyadrov** [comment]
There you go: #220

**Comment by kondrak** [comment]
I have just ran into exact same issue with 1.1.82.1 - VK_FORMAT_R32G32B32_SFLOAT is not supported. Going back to 1.1.77.0 works fine - @olegyadrov have you made any additional changes apart from updating the SDK?

**Comment by kondrak** [comment]
I'm looking at the VERSIONS.txt bundled with the SDK and according to it, 1.1.82.1 shipped with MoltenVK from a commit before the fix was introduced (d2aea46) - are you still using the latest master revision of MoltenVK by any chance?

**Comment by billhollings** [comment]
@kondrak 

I believe the SDK might still have the version of MoltenVK prior to this fix. You will probably need to pull from here and build MoltenVK...at least until the next SDK release.

**Comment by kondrak** [comment]
Thanks! That just confirms my observation.
