### ISSUE TITLE
Possible regression in Khronos buffer_device_address sample in MoltenVK 1.2.8

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2277]
The official Khronos _buffer_device_address_ sample (https://github.com/KhronosGroup/Vulkan-Samples) stopped working in SDK 280/MVK 1.2.8.  Also failing with MVK 1.2.10.

~~However, I believe it still works on Apple Silicon.  I wonder if there is an offset or other architecture-specific difference that showed up in later MVK builds?~~  Retested on Apple Silicon and failing the same way (sorry for confusion).

See the following pics:

Ventura 13.6.6/Xcode 15.2 + SDK 275/MVK 1.2.7:
![Screenshot 2024-07-18 at 11 28 11 AM](https://github.com/user-attachments/assets/d7a3a313-2559-4f5d-b48a-b2f3d5ee9e63)

Ventura 13.6.6/Xcode 15.2 + SDK 280/MVK 1.2.8 & SDK 283/MVK 1.2.9 & MVK 1.2.10:
![Screenshot 2024-07-18 at 11 24 56 AM](https://github.com/user-attachments/assets/6d614321-4789-4d1d-8ac9-18246d816122)

**Comment by billhollings** [comment]
PR #2286 fixes this. Please retest with latest MoltenVK and close this issue if the problem is corrected.

**Comment by SRSaunders** [comment]
I can confirm this change works on macOS (tested on Ventura 13.6.6).  However, this does not seem to fix things on iOS (tested on iPhone 15/iOS 17.5.1).

**Comment by billhollings** [comment]
> I can confirm this change works on macOS (tested on Ventura 13.6.6). However, this does not seem to fix things on iOS (tested on iPhone 15/iOS 17.5.1).

The stalled screen on iOS was due to a `main_loop()` error in the samples app for iOS. I've submitted [a PR](https://github.com/KhronosGroup/Vulkan-Samples/pull/1120) to the Vulkan-Samples repo to fix that.

**Comment by SRSaunders** [comment]
> The stalled screen on iOS was due to a main_loop() error in the samples app for iOS. I've submitted https://github.com/KhronosGroup/Vulkan-Samples/pull/1120 to the Vulkan-Samples repo to fix that.

I had already patched the `main_loop()` vs. `main_loop_frame()` problem for my own testing, but your solution seems to go deeper with `uses_internal_looping()`.  I will try out your PR and report back.  Thanks.

**Comment by SRSaunders** [comment]
Using the most recent MoltenVK build, the only required fix on iOS is changing `main_loop_frame()` to `main_loop()`, which I had already done.  The `uses_internal_looping()` logic does not seem to be required.  It works without it.

I am confused, since your original #2286 fix (commit 168f3ecca19e283be12b6f67003c8d4f9d814089) now seems to be enough to make it work on iOS as well as macOS.  I am left wondering whether I made a mistake creating a debug iOS MVK build and linking to a release directory or vice-versa.  Kind of embarrassed about this.
