### ISSUE TITLE
Fix the effect of rasterizerDiscardEnable on fragment shader compilation

### ISSUE THREAD

**Issue by 741g** [KhronosGroup/MoltenVK#317]
MoltenVK version: 1.0.24

Original GLSL:

    #version 450
    #extension GL_ARB_separate_shader_objects : enable
    
    out gl_PerVertex {
        vec4 gl_Position;
    };
    
    layout (std140, binding = 0) uniform Transform {
        mat4 mvp;
    } transform;
    
    layout (location = 0) in vec2 pos;
    layout (location = 1) in vec2 color;
    
    layout (location = 0) out vec2 color_varying;
    
    void main() {
        gl_Position = transform.mvp * vec4(pos, 0.0, 1.0);
        color_varying = color;
    }
    
    // fragment shader
    
    #version 450
    #extension GL_ARB_separate_shader_objects : enable
    
    layout (location = 0) in vec2 color_varying;
    layout (location = 0) out vec4 fragcolor;
    void main() {
        fragcolor = vec4(color_varying.x, 0.2, color_varying.y, 1.0);
    }

SPIRV (using glslangValidator from macos vulkan sdk 1.1.82)

    [mvk-info] Converting SPIR-V:
    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 7
    ; Bound: 39
    ; Schema: 0
                   OpCapability Shader
              %1 = OpExtInstImport "GLSL.std.450"
                   OpMemoryModel Logical GLSL450
                   OpEntryPoint Vertex %4 "main" %13 %25 %36 %37
                   OpSource GLSL 450
                   OpSourceExtension "GL_ARB_separate_shader_objects"
                   OpName %4 "main"
                   OpName %11 "gl_PerVertex"
                   OpMemberName %11 0 "gl_Position"
                   OpMemberName %11 1 "gl_PointSize"
                   OpMemberName %11 2 "gl_ClipDistance"
                   OpMemberName %11 3 "gl_CullDistance"
                   OpName %13 ""
                   OpName %17 "Transform"
                   OpMemberName %17 0 "mvp"
                   OpName %19 "transform"
                   OpName %25 "pos"
                   OpName %36 "color_varying"
                   OpName %37 "color"
                   OpMemberDecorate %11 0 BuiltIn Position
                   OpMemberDecorate %11 1 BuiltIn PointSize
                   OpMemberDecorate %11 2 BuiltIn ClipDistance
                   OpMemberDecorate %11 3 BuiltIn CullDistance
                   OpDecorate %11 Block
                   OpMemberDecorate %17 0 ColMajor
                   OpMemberDecorate %17 0 Offset 0
                   OpMemberDecorate %17 0 MatrixStride 16
                   OpDecorate %17 Block
                   OpDecorate %19 DescriptorSet 0
                   OpDecorate %19 Binding 0
                   OpDecorate %25 Location 0
                   OpDecorate %36 Location 0
                   OpDecorate %37 Location 1
              %2 = OpTypeVoid
              %3 = OpTypeFunction %2
              %6 = OpTypeFloat 32
              %7 = OpTypeVector %6 4
              %8 = OpTypeInt 32 0
              %9 = OpConstant %8 1
             %10 = OpTypeArray %6 %9
             %11 = OpTypeStruct %7 %6 %10 %10
             %12 = OpTypePointer Output %11
             %13 = OpVariable %12 Output
             %14 = OpTypeInt 32 1
             %15 = OpConstant %14 0
             %16 = OpTypeMatrix %7 4
             %17 = OpTypeStruct %16
             %18 = OpTypePointer Uniform %17
             %19 = OpVariable %18 Uniform
             %20 = OpTypePointer Uniform %16
             %23 = OpTypeVector %6 2
             %24 = OpTypePointer Input %23
             %25 = OpVariable %24 Input
             %27 = OpConstant %6 0
             %28 = OpConstant %6 1
             %33 = OpTypePointer Output %7
             %35 = OpTypePointer Output %23
             %36 = OpVariable %35 Output
             %37 = OpVariable %24 Input
              %4 = OpFunction %2 None %3
              %5 = OpLabel
             %21 = OpAccessChain %20 %19 %15
             %22 = OpLoad %16 %21
             %26 = OpLoad %23 %25
             %29 = OpCompositeExtract %6 %26 0
             %30 = OpCompositeExtract %6 %26 1
             %31 = OpCompositeConstruct %7 %29 %30 %27 %28
             %32 = OpMatrixTimesVector %7 %22 %31
             %34 = OpAccessChain %33 %13 %15
                   OpStore %34 %32
             %38 = OpLoad %23 %37
                   OpStore %36 %38
                   OpReturn
                   OpFunctionEnd
    
    End SPIR-V
    
    Converted MSL:
    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct Transform
    {
        float4x4 mvp;
    };
    
    struct main0_out
    {
        float2 color_varying [[user(locn0)]];
        float4 gl_Position [[position]];
    };
    
    struct main0_in
    {
        float2 pos [[attribute(0)]];
        float2 color [[attribute(1)]];
    };
    
    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////
    // is this supposed to be returning |out| here?/////////////////////////////////
    vertex void main0(main0_in in [[stage_in]], constant Transform& transform [[buffer(0)]])
    {
        main0_out out = {};
        out.gl_Position = transform.mvp * float4(in.pos, 0.0, 1.0);
        out.color_varying = in.color;
        out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
    }
    
    
    End MSL
    
    Estimated original GLSL:
    #version 450
    
    layout(binding = 0, std140) uniform Transform
    {
        mat4 mvp;
    } transform;
    
    layout(location = 0) in vec2 pos;
    layout(location = 0) out vec2 color_varying;
    layout(location = 1) in vec2 color;
    
    void main()
    {
        gl_Position = transform.mvp * vec4(pos, 0.0, 1.0);
        color_varying = color;
    }
    
    
    End GLSL
    
    
    [mvk-debug] Performance to compile MSL source code into a MTLLibrary curr: 0.180 ms, avg: 0.206 ms, min: 0.180 ms, max: 0.231 ms, count: 2
    [mvk-debug] Performance to retrieve shader library from the cache curr: 28.808 ms, avg: 28.808 ms, min: 28.808 ms, max: 28.808 ms, count: 1
    [mvk-debug] Performance to retrieve a MTLFunction from a MTLLibrary curr: 0.005 ms, avg: 0.005 ms, min: 0.005 ms, max: 0.005 ms, count: 1
    [mvk-debug] Performance to convert SPIR-V to MSL source code curr: 0.877 ms, avg: 2.636 ms, min: 0.877 ms, max: 4.394 ms, count: 2
    [mvk-info] Converting SPIR-V:
    ; SPIR-V
    ; Version: 1.0
    ; Generator: Khronos Glslang Reference Front End; 7
    ; Bound: 24
    ; Schema: 0
                   OpCapability Shader
              %1 = OpExtInstImport "GLSL.std.450"
                   OpMemoryModel Logical GLSL450
                   OpEntryPoint Fragment %4 "main" %9 %12
                   OpExecutionMode %4 OriginUpperLeft
                   OpSource GLSL 450
                   OpSourceExtension "GL_ARB_separate_shader_objects"
                   OpName %4 "main"
                   OpName %9 "fragcolor"
                   OpName %12 "color_varying"
                   OpDecorate %9 Location 0
                   OpDecorate %12 Location 0
              %2 = OpTypeVoid
              %3 = OpTypeFunction %2
              %6 = OpTypeFloat 32
              %7 = OpTypeVector %6 4
              %8 = OpTypePointer Output %7
              %9 = OpVariable %8 Output
             %10 = OpTypeVector %6 2
             %11 = OpTypePointer Input %10
             %12 = OpVariable %11 Input
             %13 = OpTypeInt 32 0
             %14 = OpConstant %13 0
             %15 = OpTypePointer Input %6
             %18 = OpConstant %6 0.200000003
             %19 = OpConstant %13 1
             %22 = OpConstant %6 1
              %4 = OpFunction %2 None %3
              %5 = OpLabel
             %16 = OpAccessChain %15 %12 %14
             %17 = OpLoad %6 %16
             %20 = OpAccessChain %15 %12 %19
             %21 = OpLoad %6 %20
             %23 = OpCompositeConstruct %7 %17 %18 %21 %22
                   OpStore %9 %23
                   OpReturn
                   OpFunctionEnd
    
    End SPIR-V
    
    Converted MSL:
    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct main0_out
    {
        float4 fragcolor [[color(0)]];
    };
    
    struct main0_in
    {
        float2 color_varying [[user(locn0)]];
    };
    
    fragment main0_out main0(main0_in in [[stage_in]])
    {
        main0_out out = {};
        out.fragcolor = float4(in.color_varying.x, 0.2, in.color_varying.y, 1.0);
        return out;
    }
    
    
    End MSL
    
    Estimated original GLSL:
    #version 450
    
    layout(location = 0) out vec4 fragcolor;
    layout(location = 0) in vec2 color_varying;
    
    void main()
    {
        fragcolor = vec4(color_varying.x, 0.2, color_varying.y, 1.0);
    }
    
    
    End GLSL
    
    
    [mvk-debug] Performance to compile MSL source code into a MTLLibrary curr: 0.126 ms, avg: 0.179 ms, min: 0.126 ms, max: 0.231 ms, count: 3
    [mvk-debug] Performance to retrieve shader library from the cache curr: 22.515 ms, avg: 25.662 ms, min: 22.515 ms, max: 28.808 ms, count: 2
    [mvk-debug] Performance to retrieve a MTLFunction from a MTLLibrary curr: 0.001 ms, avg: 0.003 ms, min: 0.001 ms, max: 0.005 ms, count: 2
    [***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (error code 1):
    Link failed: fragment input user(locn0) was not found in vertex shader outputs.

**Comment by billhollings** [comment]
@741g 

Yes...this is strange. As you indicate...`out` should be returned by the vertex function.

As this is a shader conversion issue...can you submit this issue to [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross/issues)? It will have to be fixed there.

**Comment by 741g** [comment]
Got it, submitted here:

https://github.com/KhronosGroup/SPIRV-Cross/issues/735

**Comment by billhollings** [comment]
@741g 

As per the discussion in https://github.com/KhronosGroup/SPIRV-Cross/issues/735, Metal requires that when rasterization is disabled, the vertex function must return `void`...so that is expected behaviour. There is no mention in Metal docs about having to remove the fragment shader...but it may be necessary if the link error is caused by input expectations of the fragment shader.

**Comment by billhollings** [comment]
@741g 

As discussed in https://github.com/KhronosGroup/SPIRV-Cross/issues/735, you had `rasterizerDiscardEnable` turned on, which caused the vertex shader to output `void`...as required by Metal.

What is your use case for turning on `rasterizerDiscardEnable`? Is there a reason why you still assign a fragment function to the pipeline? 

If there is a use case for it...perhaps MoltenVK could ignore the fragment function if `rasterizerDiscardEnable` is turned on.

**Comment by 741g** [comment]
I actually didn't have a real use case for that; I ended up misunderstanding what rasterizerDiscardEnable actually did, thinking it was more about early Z rejection or something.

So this issue to me is actually resolved, but it would be cool to see what the spec says about this kind of thing.

**Comment by francoisbertelatschrodinger** [comment]
I faced this issue as well where by mistake I set rasterizerDiscardEnable to true. It would be nice if MoltenVK was giving a more relevant error message at its own level. Beyond multi platform portability, one reason to use MoltenVK is to ignore Metal details or not even learn about Metal. A Metal error message is hard to interpret, specially when the Metal shader code itself is generated.

Or should this error message come from a Vulkan SDK layer instead? With the  "VK_LAYER_LUNARG_standard_validation" layer enabled, I haven't seen any message prior to this Metal message.

**Comment by billhollings** [comment]
@francoisbertelatschrodinger

What behaviour do you think MoltenVK should take when `rasterizerDiscardEnable` is turned on?

1. Silently remove the fragment shader
2. Leave the fragment shader in place and return/log an error to the effect that the fragment shader should not have been included
3. Both 1 & 2 (remove the fragment shader and return/log an error to the effect that the fragment shader should not have been included)
4. None of the above (and if so...what?)

**Comment by francoisbertelatschrodinger** [comment]
@billhollings 

I think behavior 2 is a minimum as this is very informative for the developer that something is wrong. Behavior 1 alone sounds dangerous.

Having 1 in addition to 2 depends on how other Vulkan implementations on other OSes behave. If someone develops an application on Linux, Windows or Android and that application executes properly with that mistake in it, then this person would expect the app to run on macOS/iOS with no modification for portability. I can try to execute a test with that mistake on Linux/NVIDIA and get back to you by Tuesday to give you a point of comparison. It could also be covered by a unit test in the Vulkan conformance test suite.
 
Of course, the best would be to find somewhere in the Vulkan spec a line about validation that deals with this situation but I have not found any so far. In this was the case, this issue would be better addressed by a SDK layer (this would be behavior 4).

**Comment by billhollings** [comment]
@francoisbertelatschrodinger 

Okay...I'm reopening this so we can get something added to MoltenVK.

Yes...the Vulkan spec is somewhat terse on how `rasterizerDiscardEnable` is to be used.

If you are able to test this use case on another Vulkan implementation...that would be great. Let me know what you find.

In the meantime...I'll investigate the CTS tests on this.

**Comment by francoisbertelatschrodinger** [comment]
I tried this on Linux/NVIDIA (CentOS 7.5.1804), NVIDIA Quadro M4000, driver 384.111. I don't get any error message at creation time of a graphics pipeline for which I pass a fragment shader and set rasterizerDiscardEnable to true. I don't get any error message from VK_LAYER_LUNARG_standard_validation neither.

**Comment by billhollings** [comment]
This is fixed in PR #375. Please retest and close if working.

**Comment by francoisbertelatschrodinger** [comment]
Sorry to report that I still the same error message:
`
[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (error code 1):
Link failed: fragment input user(locn0) was not found in vertex shader outputs.
`
I am providing the vertex shader and the fragment shader below in GLSL, it can help you to reproduce the issue:

myshader.vert:
```
#version 450
#extension GL_ARB_separate_shader_objects : enable
layout(set = 0, binding = 0) uniform buf
{
    mat4 MVP;
}
ubuf;

layout(location = 0) in vec3 inPosition;
layout(location = 0) out vec3 frag_pos; // used to compute local normal in fs

void main()
{
    gl_Position = ubuf.MVP * vec4(inPosition, 1.0);
    frag_pos = gl_Position.xyz;
}
```
myshader.frag:
```
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec3 frag_pos;
layout(location = 0) out vec4 uFragColor;

const vec3 lightDir = vec3(0.424, 0.566, 0.707);

void main()
{
        vec3 dX = dFdx(frag_pos);
        vec3 dY = dFdy(frag_pos);
        vec3 normal = normalize(cross(dX, dY));
        float light = max(0.0, dot(lightDir, normal));
        uFragColor = vec4(1.0, 1.0, 1.0, 1.0) * light;
}
```

Best,

**Comment by billhollings** [comment]
@francoisbertelatschrodinger 

That very strange. MoltenVK should now only be including a fragment shader in the pipeline if rasterization is enabled.

Can you try breaking at the following lines and determine what the value of `shaderContext.options.isRasterizationDisabled` is set to in each case, please?
- `MVKPipeline.mm:308` (after `initMVKShaderConverterContext()` is run)
- `MVKPipeline.mm:346`(test whether fragment shader should be included)

Thanks.

**Comment by billhollings** [comment]
@francoisbertelatschrodinger Thanks. Closing.
