### ISSUE TITLE
MSAA array textures not supported

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/MoltenVK#647]
It doesn't seem like MoltenVK correctly supports MSAA array textures (`sampler2DMSArray` in GLSL). When trying to compile a pipeline that uses it I get output like this in the debugger:

```

[mvk-info] Shader library compilation succeeded with warnings (Error code 4):
Compilation succeeded with: 

program_source:40:16: warning: unused variable '_582'
constant float _582 = {};
               ^

2019-06-21 12:04:46.037238+0100 renderdoccmd[51801:130723] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-06-21 12:04:46.037308+0100 renderdoccmd[51801:130723] MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 1 try
2019-06-21 12:04:46.101949+0100 renderdoccmd[51801:130723] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-06-21 12:04:46.102039+0100 renderdoccmd[51801:130723] MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 2 try
2019-06-21 12:04:46.189082+0100 renderdoccmd[51801:130723] Compiler failed with XPC_ERROR_CONNECTION_INTERRUPTED
2019-06-21 12:04:46.189144+0100 renderdoccmd[51801:130723] MTLCompiler: Compilation failed with XPC_ERROR_CONNECTION_INTERRUPTED on 3 try
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 1):
Compiler encountered an internal error.
Error   - Failed creating object Pipeline at line 1761, vkr was VK_ERROR_INITIALIZATION_FAILED
Process 51801 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGTRAP
```

btw I ended up on a bit of a red-herring tangent when trying to build the shader in the standalone compiler to examine it for errors, because the shader doesn't have bindings remapped (e.g. this shader uses fewer than 16 samplers but some of them have index >= 15, which fails to compile. Or overlapping bindings due to arrays that only consume one binding slot in vulkan but multiple in metal).

The SPIR-V shader assembly in question: [repro.txt](https://github.com/KhronosGroup/MoltenVK/files/3314222/repro.txt)

**Comment by HansKristian-Work** [comment]
The automatic resource mapping should be fixed in https://github.com/KhronosGroup/SPIRV-Cross/pull/1036, but I don't think that's going to be relevant for MoltenVK runtime at least.

**Comment by billhollings** [comment]
> It seems like the MoltenVK offline tool is not using add_resource_binding API since I assume it has no knowledge about the pipeline layout. Do you know if the resulting MSL is supposed to be useable in MoltenVK as a pre-baked shader?

MSL shaders converted using the external tool need to be used in pipelines that reference their resources in a compatible way.

@baldurk What's the status of this issue? If a problem still exists...can you provide a way to replicate it in MoltenVK, please?

**Comment by baldurk** [comment]
Yes the issue still exists the same as described in the original post, I just tested latest MoltenVK. The shader given above will still repro the problem, what else would be useful for you?

**Comment by alecazam** [comment]
The renderPipeline for MSAA array textures has to know the primitiveType or the renderPipeline fails to compile.  This ties draw calls to the renderPipeline created.

pipelineDescriptor.inputPrimitiveTopology = .triangles
