### ISSUE TITLE
VK_EXT_metal_surface extension is not reported correctly

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/MoltenVK#720]
When calling `vkCreateMacOSSurfaceMVK()` I get a message that it's obsolete and I should be using `vkCreateMetalSurfaceEXT()` from `VK_EXT_metal_surface`. However that extension is not reported as supported via `vkEnumerateInstanceExtensionProperties`.

Looking at the output from vulkaninfo, I see that the extension _is_ reported but incorrectly as a device extension. There are also some other instance extensions like `VK_KHR_surface` as well as `VK_MVK_macos_surface` that are incorrectly enumerated as device extensions.

I tested with the SDK 1.1.114 loader and vulkaninfo, and with the MoltenVK both from that SDK as well as built from latest source.

**Comment by cdavis5e** [comment]
The loader does not yet support that extension.

**Comment by billhollings** [comment]
MoltenVK does not correctly discriminate between the lists returned by the two calls `vkEnumerateInstanceExtensionProperties()` and `vkEnumerateDeviceExtensionProperties()`. It should.

**Comment by billhollings** [comment]
@baldurk The reporting of the instance and device extensions is now fixed in PR #723 . Please retest and close this issue if it works. 

As @cdavis5e indicates, the reporting of `VK_EXT_metal_surface` works for MoltenVK, but is not supported by the loader yet.

**Comment by baldurk** [comment]
I can test that the device extension list doesn't include any instance extensions and vice-versa, but it sounds like the core issue that I reported is still a problem if I can't use `VK_EXT_metal_surface`.

Maybe the message about deprecation should be removed until `VK_EXT_metal_surface` is usable?

**Comment by billhollings** [comment]
> it sounds like the core issue that I reported is still a problem if I can't use `VK_EXT_metal_surface`.

That core issue needs to be fixed in the layers implementation in the SDK. If you have not done so yet, can you [post an issue](https://vulkan.lunarg.com/issue/home) there, please?

> Maybe the message about deprecation should be removed until `VK_EXT_metal_surface` is usable?

`VK_EXT_metal_surface` is usable within MoltenVK...which is where the deprecation message is originating. Although we encourage the use of the SDK, a number of developers use MoltenVK by itself.

**Comment by baldurk** [comment]
It's not an SDK wide issue so I looked instead on the Vulkan-Loader repository, and it seems like there's already an issue for this - https://github.com/KhronosGroup/Vulkan-Loader/issues/207

> `VK_EXT_metal_surface` is usable within MoltenVK...which is where the deprecation message is originating. Although we encourage the use of the SDK, a number of developers use MoltenVK by itself.

I understand that MoltenVK can be used directly without the loader, but what I mean is that it seems premature to deprecate the `MVK` surface extensions when for many people the new extension they have been deprecated in favour of is not available.

As you say that is the encouraged path use the loader, so hopefully most users are doing that. Having a deprecation notice that can't be fixed when using the encouraged path is kind of confusing. It doesn't do any harm to users calling MoltenVK directly to not get a deprecation notice yet.

**Comment by billhollings** [comment]
>it seems premature to deprecate the MVK surface extensions when for many people the new extension they have been deprecated in favour of is not available.

The offending log message has been removed.

The `VK_EXT_metal_surface` is [being added](https://github.com/KhronosGroup/Vulkan-Loader/pull/243) to the loader for the next SDK release.

Closing this now.
